// <auto-generated />
using System;
using ArielCRM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArielCRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621130033_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AccessLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<int>("Access")
                        .HasColumnType("integer")
                        .HasColumnName("access_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("access_levels");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AccessLevelPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_level_id");

                    b.Property<string>("PermissionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("permission_id");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("AccessLevelId", "PermissionId")
                        .IsUnique();

                    b.ToTable("access_level_permissions");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.ActivityLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("performed_by");

                    b.Property<string>("RelatedId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_id");

                    b.Property<string>("RelatedTo")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("related_to");

                    b.Property<string>("TicketTaskTaskId")
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_activity_dt");

                    b.HasIndex("TicketTaskTaskId");

                    b.ToTable("activity_log");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("ActionDescription")
                        .HasColumnType("text")
                        .HasColumnName("action_description");

                    b.Property<string>("ActionTypeRaw")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_type");

                    b.Property<string>("AffectedFields")
                        .HasColumnType("text")
                        .HasColumnName("affected_fields");

                    b.Property<string>("BatchId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("batch_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("DiffData")
                        .HasColumnType("text")
                        .HasColumnName("diff_data");

                    b.Property<string>("EntityDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("entity_display_name");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("entity_url");

                    b.Property<string>("ExtraMetadata")
                        .HasColumnType("text")
                        .HasColumnName("extra_metadata");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initiated_at");

                    b.Property<string>("InitiatedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("initiated_by_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsReverted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_reverted");

                    b.Property<string>("ParentAuditId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_audit_id");

                    b.Property<string>("PreviousState")
                        .HasColumnType("text")
                        .HasColumnName("previous_state");

                    b.Property<string>("RevertTypeRaw")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("revert_type");

                    b.Property<DateTime?>("RevertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reverted_at");

                    b.Property<string>("RevertedById")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reverted_by_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceRaw")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<string>("StatusRaw")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UpdatedState")
                        .HasColumnType("text")
                        .HasColumnName("updated_state");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeRaw")
                        .HasDatabaseName("idx_auditlog_action");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("idx_auditlog_batch");

                    b.HasIndex("InitiatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_auditlog_date");

                    b.HasIndex("InitiatedById")
                        .HasDatabaseName("idx_auditlog_initiator");

                    b.HasIndex("IsReverted")
                        .HasDatabaseName("idx_auditlog_reverted");

                    b.HasIndex("ParentAuditId")
                        .HasDatabaseName("idx_auditlog_parent");

                    b.HasIndex("RevertedById");

                    b.HasIndex("EntityName", "EntityId")
                        .HasDatabaseName("idx_auditlog_entity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AuditRevertHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AuditLogId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("RevertNote")
                        .HasColumnType("text")
                        .HasColumnName("revert_note");

                    b.Property<DateTime>("RevertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reverted_at");

                    b.Property<string>("RevertedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reverted_by_id");

                    b.Property<string>("SnapshotAfterRevert")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_after_revert");

                    b.Property<string>("SnapshotBeforeRevert")
                        .HasColumnType("text")
                        .HasColumnName("snapshot_before_revert");

                    b.HasKey("Id");

                    b.HasIndex("AuditLogId")
                        .HasDatabaseName("idx_reverthistory_auditlog");

                    b.HasIndex("RevertedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_reverthistory_date");

                    b.HasIndex("RevertedById");

                    b.ToTable("audit_revert_history", (string)null);
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Comment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("ActivityLogId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activity_log_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Edited")
                        .HasColumnType("boolean")
                        .HasColumnName("edited");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ticket_id");

                    b.Property<string>("TicketTaskTaskId")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ActivityLogId");

                    b.HasIndex("TicketTaskTaskId");

                    b.HasIndex("UserId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("designation");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.CrmTask", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DealId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("deal_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("LeadId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("DealId")
                        .HasDatabaseName("idx_tasks_deal");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("idx_tasks_due");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("idx_tasks_lead");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Deal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_to");

                    b.Property<DateOnly>("CloseDate")
                        .HasColumnType("date")
                        .HasColumnName("close_date");

                    b.Property<string>("ContactId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProjectId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<decimal>("Value")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("ContactId")
                        .HasDatabaseName("idx_deals_contact");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Stage")
                        .HasDatabaseName("idx_deals_stage");

                    b.ToTable("deals");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Designation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("designations");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Documents", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("upload_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Lead", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_to");

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("budget");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("company");

                    b.Property<string>("ContactId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DealCloseDate")
                        .HasColumnType("date")
                        .HasColumnName("deal_close_date");

                    b.Property<DateOnly>("DealStartDate")
                        .HasColumnType("date")
                        .HasColumnName("deal_start_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("project_title");

                    b.Property<int>("ProjectType")
                        .HasColumnType("integer")
                        .HasColumnName("project_type");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId")
                        .HasDatabaseName("idx_leads_assigned");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_leads_status");

                    b.ToTable("leads");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Meeting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("LeadId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lead_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("idx_meetings_date");

                    b.HasIndex("LeadId");

                    b.ToTable("meetings");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("created_by_name");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<string>("RelatedId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_id");

                    b.Property<string>("RelatedTo")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("related_to");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RelatedTo", "RelatedId")
                        .HasDatabaseName("idx_notes_lookup");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("ContactId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_key");

                    b.Property<string>("ProjectLeadId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_lead_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.HasIndex("ProjectKey")
                        .IsUnique()
                        .HasDatabaseName("idx_projects_key");

                    b.HasIndex("ProjectLeadId")
                        .HasDatabaseName("idx_projects_lead");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assigned_to");

                    b.Property<string>("ClientId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("ticket_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId")
                        .HasDatabaseName("idx_tickets_assigned");

                    b.HasIndex("ClientId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_tickets_status");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.TicketTask", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("task_id");

                    b.Property<string>("AssignToId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assign_to_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("project_id");

                    b.Property<string>("ReportedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reported_by_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("TicketId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignToId")
                        .HasDatabaseName("idx_tickettasks_assigned");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_tickettasks_project");

                    b.HasIndex("ReportedById")
                        .HasDatabaseName("idx_tickettasks_reported");

                    b.ToTable("ticket_tasks", (string)null);
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("AccessLevelId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("department_id");

                    b.Property<string>("DesignationId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("designation_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_image");

                    b.HasKey("Id");

                    b.HasIndex("AccessLevelId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("project_members", b =>
                {
                    b.Property<string>("project_id")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("user_id")
                        .HasColumnType("character varying(50)");

                    b.HasKey("project_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AccessLevelPermission", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.AccessLevel", "AccessLevel")
                        .WithMany("Permissions")
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.Permission", "Permission")
                        .WithMany("AccessLevels")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.ActivityLog", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.TicketTask", null)
                        .WithMany("ActivityLogs")
                        .HasForeignKey("TicketTaskTaskId");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AuditLog", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.User", "InitiatedBy")
                        .WithMany()
                        .HasForeignKey("InitiatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.AuditLog", "ParentAudit")
                        .WithMany()
                        .HasForeignKey("ParentAuditId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArielCRM.DataLayer.Entities.User", "RevertedBy")
                        .WithMany()
                        .HasForeignKey("RevertedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InitiatedBy");

                    b.Navigation("ParentAudit");

                    b.Navigation("RevertedBy");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AuditRevertHistory", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.AuditLog", "AuditLog")
                        .WithMany()
                        .HasForeignKey("AuditLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.User", "RevertedBy")
                        .WithMany()
                        .HasForeignKey("RevertedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuditLog");

                    b.Navigation("RevertedBy");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Comment", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.ActivityLog", "ActivityLog")
                        .WithMany()
                        .HasForeignKey("ActivityLogId");

                    b.HasOne("ArielCRM.DataLayer.Entities.TicketTask", null)
                        .WithMany("Comments")
                        .HasForeignKey("TicketTaskTaskId");

                    b.HasOne("ArielCRM.DataLayer.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.CrmTask", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.User", "AssignedTo")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.Deal", "Deal")
                        .WithMany("Tasks")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArielCRM.DataLayer.Entities.Lead", "Lead")
                        .WithMany("Tasks")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");

                    b.Navigation("Deal");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Deal", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.User", "AssignedTo")
                        .WithMany("AssignedDeals")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("ArielCRM.DataLayer.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Contact");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Designation", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Documents", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.Project", "Project")
                        .WithMany("Documents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Lead", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.User", "AssignedTo")
                        .WithMany("AssignedLeads")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.Contact", "Contact")
                        .WithOne("Lead")
                        .HasForeignKey("ArielCRM.DataLayer.Entities.Lead", "ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Meeting", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.Lead", "Lead")
                        .WithMany("Meetings")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Project", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.Contact", "Contact")
                        .WithOne("Project")
                        .HasForeignKey("ArielCRM.DataLayer.Entities.Project", "ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ArielCRM.DataLayer.Entities.User", "ProjectLead")
                        .WithMany("LedProjects")
                        .HasForeignKey("ProjectLeadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contact");

                    b.Navigation("ProjectLead");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Ticket", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.User", "AssignedTo")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.Contact", "Client")
                        .WithMany("Tickets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.TicketTask", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.User", "AssignedUser")
                        .WithMany("AssignedProjTickets")
                        .HasForeignKey("AssignToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArielCRM.DataLayer.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.User", "ReportedUser")
                        .WithMany("ReportedProjTickets")
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("Project");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.User", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.AccessLevel", "AccessLevel")
                        .WithMany()
                        .HasForeignKey("AccessLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.Designation", "Designation")
                        .WithMany("Users")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessLevel");

                    b.Navigation("Department");

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("project_members", b =>
                {
                    b.HasOne("ArielCRM.DataLayer.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArielCRM.DataLayer.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.AccessLevel", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Contact", b =>
                {
                    b.Navigation("Lead");

                    b.Navigation("Project")
                        .IsRequired();

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Deal", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Designation", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Lead", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Permission", b =>
                {
                    b.Navigation("AccessLevels");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.Project", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.TicketTask", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ArielCRM.DataLayer.Entities.User", b =>
                {
                    b.Navigation("AssignedDeals");

                    b.Navigation("AssignedLeads");

                    b.Navigation("AssignedProjTickets");

                    b.Navigation("AssignedTasks");

                    b.Navigation("AssignedTickets");

                    b.Navigation("LedProjects");

                    b.Navigation("ReportedProjTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
