export enum DepartmentKey {
    ADMINISTRATION = 'ADMINISTRATION',
    DEVELOPMENT = 'DEVELOPMENT',
    BUSINESS_MANAGEMENT = 'BUSINESS_MANAGEMENT',
    DESIGN = 'DESIGN',
    SUPPORT = 'SUPPORT',
    PROJECT_MANAGEMENT = 'PROJECT_MANAGEMENT',
    HUMAN_RESOURCES = 'HUMAN_RESOURCES'
}   